- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: true # DeltaV - Can be antagonist
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: BookScientistsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
