- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    back: ClothingBackpackRoboticsFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatRobo
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
  innerClothingSkirt: ClothingUniformJumpskirtRoboticist
  satchel: ClothingBackpackSatchelRoboticsFilled
  duffelbag: ClothingBackpackDuffelRoboticsFilled
