- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatRnd
    id: SciencePDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled

- type: startingGear
  id: ScientistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitScientist
    head: ClothingHeadEnvirohelmScientist
    gloves: ClothingHandsGlovesEnviroglovesWhite
